fix: remove most of qt deprecation warnings
brezerk/q4wine pull request #189
Opened 2021-11-12 21:54 UTC by jedrzejowski

I have made following changes:
 - `endl -> `Qt::endl`
 - `left` -> `Qt::left`
 
This will remove almost every warning from compiler.

2021-11-15 12:31 UTC, brezerk commented
hi @jedrzejowski 

Thanks a lot for PR. I'll review it today.

Thanks!

2021-11-15 23:00 UTC, brezerk requested changes
Looks good overall. Few items to address. Also not sure about `override` identifier.

2021-11-20 15:34 UTC, jedrzejowski commented on src/q4wine-gui/prefixsettings.h
> +        void comboTemplatesList_Change(int id);
I still do not understand why `const int`, it should be `int` or `const int&`.
When you are using `const int`, the value is being copied while executing.

2021-11-29 20:58 UTC, brezerk commented on src/q4wine-gui/prefixsettings.h
> +        void comboTemplatesList_Change(int id);
you are quite right, however you should update both constructor and function to match in this case. unless I am missing something :)

2022-01-08 22:09 UTC, brezerk approved these changes

2022-01-08 22:11 UTC, merged

2022-01-08 22:11 UTC, brezerk commented
Looks good. Thanks a lot! 👍

2022-01-09 23:31 UTC, tehnick commented
You broke support of Ubuntu Focal and older:
https://launchpad.net/~tehnick/+archive/ubuntu/q4wine-devel/+packages
As well as all systems wit Qt < 5.15.
Is it worth it?

2022-01-09 23:42 UTC, brezerk commented
> error: ‘endl’ is not a member of ‘Qt’

Yeah, not that good. Thank you for a note.

пн, 10 янв. 2022 г., 01:31 Boris Pek ***@***.***>:

> You broke support of Ubuntu Focal and older:
> https://launchpad.net/~tehnick/+archive/ubuntu/q4wine-devel/+packages
> As well as all systems wit Qt < 5.15.
> Is it worth it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/brezerk/q4wine/pull/189#issuecomment-1008446661>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAF2DA2ETN3SPVNWZZYT2TUVILGPANCNFSM5H5YJ7TA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-05-20 22:12 UTC, tehnick commented
Just reminding that build for Ubuntu Focal still not fixed yet. Example of build log is [here](https://launchpadlibrarian.net/579385847/buildlog_ubuntu-focal-amd64.q4wine-devel_1.3.13+2+g9735939-0ppa1~focal1_BUILDING.txt.gz). Example of error:
```
/<<BUILDDIR>>/q4wine-devel-1.3.13+2+g9735939/src/q4wine-lib/q4wine-lib.cpp: In member function ‘void corelib::getBuildFlags()’:
/<<BUILDDIR>>/q4wine-devel-1.3.13+2+g9735939/src/q4wine-lib/q4wine-lib.cpp:574:53: error: ‘endl’ is not a member of ‘Qt’
  574 |     Qcout<<QObject::tr("Buildtime flags are:")<<Qt::endl<<Qt::endl;
```

Ubuntu Focal (20.04 LTS) uses Qt 5.12.8.

2022-05-20 22:19 UTC, tehnick commented
I have re-checked: even Ubuntu Bionic (18.04 LTS) was supported until this PR.
https://launchpad.net/~tehnick/+archive/ubuntu/q4wine/+packages
https://launchpad.net/~tehnick/+archive/ubuntu/q4wine-devel/+packages